;; The sequence of triangle numbers is generated by adding the natural numbers.
;; What is the value of the first triangle number to have over five hundred
;; divisors?

(ns project-euler-clojure.012)

(defn count-divisors [n]
  (->> (range 1 (Math/sqrt n))
       (filter (comp zero? (partial mod n)))
       (count)
       (* 2)))

(defn triangle [n]
  (/ (* n (inc n)) 2))

(def triangle-numbers (map triangle (iterate inc 1)))

(defn problem-012 []
  (->> (drop-while #(<= (count-divisors %) 500) triangle-numbers)
       (first)))
