;; The sequence of triangle numbers is generated by adding the natural numbers.
;; What is the value of the first triangle number to have over five hundred
;; divisors?

(ns project-euler-clojure.012)

(defn count-divisors [n]
  (->> (range 1 (Math/sqrt n))
       (filter (comp zero? (partial mod n)))
       (count)
       (* 2)))

(defn triangle-number [n]
  (/ (* n (+ n 1)) 2))

(defn problem-012 []
  (->> (iterate inc 1)
       (map triangle-number)
       (drop-while #(<= (count-divisors %) 500))
       (first)))
