# How many distinct terms are in the sequence generated by a^b 
# for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

results = Array.new
(2..100).each do |a|
    (2..100).each do |b|
        results.push(a**b)
    end
end
puts results.uniq.length