# The sequence of triangle numbers is generated by adding the natural numbers.
# What is the value of the first triangle number to have over five hundred 
# divisors?

require 'prime'

# The number of factors of a number like x^a + y^b + z^c
# is (a + 1)*(b + 1)*(c + 1)
def calculate_factors(x)
    factors = 1
    Prime.prime_division(x).each do |prime_factor|
        factors *= (prime_factor[1] + 1)
    end
    factors
end

triangle_number = 0
(1..Float::INFINITY).each do |x|
    triangle_number += x
    if calculate_factors(triangle_number) >= 500
        puts triangle_number
        exit
    end
end
